---
extends:
  - 'alloy'
  - 'alloy/typescript'
plugins:
  - chai-friendly
env:
  node: true
  mocha: true
ignorePatterns:
  - '**/*.js'
rules:
  max-classes-per-file: off
  eol-last:
    - error
    - always
  '@typescript-eslint/no-unused-expressions': off
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/no-duplicate-imports': off
