---
os: linux
dist: xenial
language: node_js
node_js: lts/*
# services:
#   - mysql
addons:
  ssh_known_hosts: beta.tygr.info

env:
  global:
    - HOST=beta.tygr.info
    - MYSQL_USER=root
    - MYSQL_HOST=127.0.0.1
    - MYSQL_PORT=3306
    - MYSQL_PASSWORD=
    - MYSQL_TEST_DB=tygr-server-test
    - JWT_SECRET=shhh

# before_script:
#   - mysql -e 'CREATE DATABASE `tygr-server-test`;'

# SSH Setup
before_deploy:
  - openssl aes-256-cbc
    -K $encrypted_db2095f63ba3_key
    -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc
    -out /tmp/deploy_rsa
    -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

script:
  - npm run quality:check
  - npm run build

deploy:
  edge: true
  on:
    branch: master
  provider: script
  script: bash scripts/deploy.sh
